---
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Ensure service enabled
  service:
    name: elasticsearch
    enabled: yes
    state: started
