---
- name: Set list of path to look for local Elasticsearch configuration directory
  set_fact:
    elasticsearch_search_config_paths: "{{ elasticsearch_search_config_paths }} + [ '{{ elasticsearch_search_config_path }}' ]"
  with_items: "{{ group_names }}"

- name: Check if Elasticsearch configuration directory exists
  stat:
    path: "{{ item }}"
  register: elasticsearch_config_check
  become: false
  delegate_to: 127.0.0.1
  with_first_found:
    - files: "{{ elasticsearch_search_config_paths }}"
      skip: true

- name: Set Elasticsearch configuration directory
  set_fact:
    elasticsearch_host_config_path: "{{ elasticsearch_config_check.results[0].stat.path }}"
  when:
    - elasticsearch_config_check.results[0] is defined
    - elasticsearch_config_check.results[0].stat is defined
    - elasticsearch_config_check.results[0].stat.isdir

- name: Check if Elasticsearch template configuration file is exists
  stat:
    path: "{{ elasticsearch_host_config_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: elasticsearch_config_check

- name: Check if Elasticsearch license file is exists
  stat:
    path: "{{ elasticsearch_host_license_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: elasticsearch_license_check

- name: Check if SSL Key file is exists
  stat:
    path: "{{ elasticsearch_host_sslkey_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: elastic_sslkey_check

- name: Check if SSL Cert file is exists
  stat:
    path: "{{ elasticsearch_host_sslcert_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: elastic_sslcert_check

- name: Check if SSL RootCA
  stat:
    path: "{{ elasticsearch_host_ca_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: elastic_sslca_check